"""The `Product` model — one row per item in the store's inventory.

Maps the `products` table from the spec (section 12): the item's name, what it
cost, what it sells for, and how many are in stock. This is the foundation the
rest of the system builds on — sales and fiado both consume stock, and profit
is the gap between `sale_price` and `cost_price`.

Written in SQLAlchemy 2.0 style: columns are declared as typed attributes with
`Mapped[...]` + `mapped_column(...)`, which gives real type hints and lets the
ORM infer a lot from the Python type.
"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Integer,
    Numeric,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Product(Base):
    # The physical table name in Postgres.
    __tablename__ = "products"

    # Table-level constraints live here (as opposed to column-level ones).
    # These CHECKs are enforced by *Postgres itself*: even if a bug in our
    # Python code tried to write a negative price or stock, the database would
    # reject the row. Enforcing money/stock rules at the database is a
    # non-negotiable — the app is not the only conceivable writer, and the DB
    # is the last line of defence. Each constraint is named so it shows up
    # clearly in error messages and migrations.
    __table_args__ = (
        CheckConstraint("cost_price >= 0", name="ck_products_cost_price_non_negative"),
        CheckConstraint("sale_price >= 0", name="ck_products_sale_price_non_negative"),
        CheckConstraint(
            "stock_quantity >= 0", name="ck_products_stock_quantity_non_negative"
        ),
    )

    # --- Primary key -------------------------------------------------------
    # A UUID generated by *Postgres*, not Python. `server_default=text(...)`
    # emits `DEFAULT gen_random_uuid()` in the table definition, so the value
    # is produced by the database on INSERT. Why server-side? The database
    # stays the single source of truth for ids — any writer (this ORM, a raw
    # SQL script, another service) gets a valid id without our app having to
    # remember to set one. `gen_random_uuid()` is built into Postgres 13+, so
    # no extension is needed (Supabase has it out of the box). `UUID(as_uuid=
    # True)` maps the column to Python `uuid.UUID` objects rather than strings.
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )

    # --- Business columns --------------------------------------------------
    # A non-Optional annotation like `Mapped[str]` tells SQLAlchemy the column
    # is NOT NULL automatically (a `Mapped[str | None]` would be nullable). We
    # still pass `nullable=False` explicitly for readability. `Text` is an
    # unbounded string; on Postgres it is equivalent to an unlimited VARCHAR.
    # (Swap in `String(120)` if you ever want to cap the length.)
    name: Mapped[str] = mapped_column(Text, nullable=False)

    # Money is stored as NUMERIC(10, 2): up to 10 total digits, 2 of them after
    # the decimal point (so max 99,999,999.99). NUMERIC is *exact* — unlike
    # float, it never drifts into errors like 0.1 + 0.2 = 0.30000000000000004.
    # SQLAlchemy maps NUMERIC to Python's `Decimal`, hence `Mapped[Decimal]`.
    # Never do money math with floats.
    cost_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    sale_price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)

    # Whole-number count of units on hand. `server_default=text("0")` makes
    # Postgres default it to 0 when no value is given, so a new item created
    # without a stock figure starts at zero rather than NULL.
    stock_quantity: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )

    # --- Timestamps --------------------------------------------------------
    # `DateTime(timezone=True)` maps to Postgres TIMESTAMPTZ (timestamp WITH
    # time zone). This matters: TIMESTAMPTZ stores an unambiguous instant, so
    # later "today in America/Sao_Paulo" math stays reliable. Plain DateTime
    # (without timezone=True) becomes TIMESTAMP WITHOUT TIME ZONE — avoid it
    # for anything time-sensitive.
    #
    # `server_default=func.now()` → Postgres sets the value on INSERT (`now()`
    # returns the current timestamptz). created_at is set once, by the
    # database, and never touched again.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # updated_at also defaults to now() on INSERT, and `onupdate=func.now()`
    # tells SQLAlchemy to set it to `now()` again on every UPDATE it issues.
    # Caveat: `onupdate` fires only for updates made *through SQLAlchemy*. A raw
    # `UPDATE` run straight against the database would not bump it — for that
    # you'd add a Postgres trigger. Since our backend is the only writer, the
    # ORM-level hook is enough for now.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
