"""create fiado_accounts table

Revision ID: 8ec834541983
Revises: 178fe6caf1c6
Create Date: 2026-08-17 04:32:16.857545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec834541983'
down_revision: Union[str, Sequence[str], None] = '178fe6caf1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiado_accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('installments_count', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('agreed_settlement_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('weekly', 'biweekly', 'monthly')", name='ck_fiado_accounts_frequency_valid'),
    sa.CheckConstraint('installment_amount >= 0', name='ck_fiado_accounts_installment_amount_non_negative'),
    sa.CheckConstraint('installments_count > 0', name='ck_fiado_accounts_installments_count_positive'),
    sa.CheckConstraint('remaining_balance >= 0', name='ck_fiado_accounts_remaining_balance_non_negative'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fiado_accounts')
    # ### end Alembic commands ###
